/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitarReceitaRouteImport } from './routes/solicitar-receita'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequisicaoInternaRouteImport } from './routes/requisicao-interna'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoInternoRouteImport } from './routes/historico-interno'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExportarRouteImport } from './routes/exportar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSetoresRouteImport } from './routes/admin.setores'
import { Route as AdminRequisicoesInternasRouteImport } from './routes/admin.requisicoes-internas'
import { Route as AdminRequisicoesRouteImport } from './routes/admin.requisicoes'
import { Route as AdminReceitasRouteImport } from './routes/admin.receitas'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminProducaoRouteImport } from './routes/admin.producao'
import { Route as AdminPerfisRouteImport } from './routes/admin.perfis'
import { Route as AdminMovimentacoesRouteImport } from './routes/admin.movimentacoes'
import { Route as AdminListaComprasRouteImport } from './routes/admin.lista-compras'
import { Route as AdminIndicadoresRouteImport } from './routes/admin.indicadores'
import { Route as AdminImportarEstoqueRouteImport } from './routes/admin.importar-estoque'
import { Route as AdminFornecedoresRouteImport } from './routes/admin.fornecedores'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as PedidoEditarIdRouteImport } from './routes/pedido.editar.$id'

const SolicitarReceitaRoute = SolicitarReceitaRouteImport.update({
  id: '/solicitar-receita',
  path: '/solicitar-receita',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisicaoInternaRoute = RequisicaoInternaRouteImport.update({
  id: '/requisicao-interna',
  path: '/requisicao-interna',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoInternoRoute = HistoricoInternoRouteImport.update({
  id: '/historico-interno',
  path: '/historico-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportarRoute = ExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetoresRoute = AdminSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequisicoesInternasRoute =
  AdminRequisicoesInternasRouteImport.update({
    id: '/requisicoes-internas',
    path: '/requisicoes-internas',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRequisicoesRoute = AdminRequisicoesRouteImport.update({
  id: '/requisicoes',
  path: '/requisicoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceitasRoute = AdminReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProducaoRoute = AdminProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfisRoute = AdminPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMovimentacoesRoute = AdminMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListaComprasRoute = AdminListaComprasRouteImport.update({
  id: '/lista-compras',
  path: '/lista-compras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndicadoresRoute = AdminIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportarEstoqueRoute = AdminImportarEstoqueRouteImport.update({
  id: '/importar-estoque',
  path: '/importar-estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFornecedoresRoute = AdminFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoEditarIdRoute = PedidoEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => PedidoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/exportar': typeof ExportarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historico': typeof HistoricoRoute
  '/historico-interno': typeof HistoricoInternoRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRouteWithChildren
  '/requisicao-interna': typeof RequisicaoInternaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitar-receita': typeof SolicitarReceitaRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/importar-estoque': typeof AdminImportarEstoqueRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/lista-compras': typeof AdminListaComprasRoute
  '/admin/movimentacoes': typeof AdminMovimentacoesRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/requisicoes': typeof AdminRequisicoesRoute
  '/admin/requisicoes-internas': typeof AdminRequisicoesInternasRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/pedido/editar/$id': typeof PedidoEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exportar': typeof ExportarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historico': typeof HistoricoRoute
  '/historico-interno': typeof HistoricoInternoRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRouteWithChildren
  '/requisicao-interna': typeof RequisicaoInternaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitar-receita': typeof SolicitarReceitaRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/importar-estoque': typeof AdminImportarEstoqueRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/lista-compras': typeof AdminListaComprasRoute
  '/admin/movimentacoes': typeof AdminMovimentacoesRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/requisicoes': typeof AdminRequisicoesRoute
  '/admin/requisicoes-internas': typeof AdminRequisicoesInternasRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/pedido/editar/$id': typeof PedidoEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/exportar': typeof ExportarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historico': typeof HistoricoRoute
  '/historico-interno': typeof HistoricoInternoRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRouteWithChildren
  '/requisicao-interna': typeof RequisicaoInternaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitar-receita': typeof SolicitarReceitaRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/importar-estoque': typeof AdminImportarEstoqueRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/lista-compras': typeof AdminListaComprasRoute
  '/admin/movimentacoes': typeof AdminMovimentacoesRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/requisicoes': typeof AdminRequisicoesRoute
  '/admin/requisicoes-internas': typeof AdminRequisicoesInternasRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/pedido/editar/$id': typeof PedidoEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/exportar'
    | '/forgot-password'
    | '/historico'
    | '/historico-interno'
    | '/login'
    | '/pedido'
    | '/requisicao-interna'
    | '/reset-password'
    | '/solicitar-receita'
    | '/admin/estoque'
    | '/admin/fornecedores'
    | '/admin/importar-estoque'
    | '/admin/indicadores'
    | '/admin/lista-compras'
    | '/admin/movimentacoes'
    | '/admin/perfis'
    | '/admin/producao'
    | '/admin/produtos'
    | '/admin/receitas'
    | '/admin/requisicoes'
    | '/admin/requisicoes-internas'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/admin/'
    | '/pedido/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exportar'
    | '/forgot-password'
    | '/historico'
    | '/historico-interno'
    | '/login'
    | '/pedido'
    | '/requisicao-interna'
    | '/reset-password'
    | '/solicitar-receita'
    | '/admin/estoque'
    | '/admin/fornecedores'
    | '/admin/importar-estoque'
    | '/admin/indicadores'
    | '/admin/lista-compras'
    | '/admin/movimentacoes'
    | '/admin/perfis'
    | '/admin/producao'
    | '/admin/produtos'
    | '/admin/receitas'
    | '/admin/requisicoes'
    | '/admin/requisicoes-internas'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/admin'
    | '/pedido/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/exportar'
    | '/forgot-password'
    | '/historico'
    | '/historico-interno'
    | '/login'
    | '/pedido'
    | '/requisicao-interna'
    | '/reset-password'
    | '/solicitar-receita'
    | '/admin/estoque'
    | '/admin/fornecedores'
    | '/admin/importar-estoque'
    | '/admin/indicadores'
    | '/admin/lista-compras'
    | '/admin/movimentacoes'
    | '/admin/perfis'
    | '/admin/producao'
    | '/admin/produtos'
    | '/admin/receitas'
    | '/admin/requisicoes'
    | '/admin/requisicoes-internas'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/admin/'
    | '/pedido/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExportarRoute: typeof ExportarRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoricoRoute: typeof HistoricoRoute
  HistoricoInternoRoute: typeof HistoricoInternoRoute
  LoginRoute: typeof LoginRoute
  PedidoRoute: typeof PedidoRouteWithChildren
  RequisicaoInternaRoute: typeof RequisicaoInternaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolicitarReceitaRoute: typeof SolicitarReceitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitar-receita': {
      id: '/solicitar-receita'
      path: '/solicitar-receita'
      fullPath: '/solicitar-receita'
      preLoaderRoute: typeof SolicitarReceitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisicao-interna': {
      id: '/requisicao-interna'
      path: '/requisicao-interna'
      fullPath: '/requisicao-interna'
      preLoaderRoute: typeof RequisicaoInternaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-interno': {
      id: '/historico-interno'
      path: '/historico-interno'
      fullPath: '/historico-interno'
      preLoaderRoute: typeof HistoricoInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportar': {
      id: '/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof ExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setores': {
      id: '/admin/setores'
      path: '/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AdminSetoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requisicoes-internas': {
      id: '/admin/requisicoes-internas'
      path: '/requisicoes-internas'
      fullPath: '/admin/requisicoes-internas'
      preLoaderRoute: typeof AdminRequisicoesInternasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requisicoes': {
      id: '/admin/requisicoes'
      path: '/requisicoes'
      fullPath: '/admin/requisicoes'
      preLoaderRoute: typeof AdminRequisicoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receitas': {
      id: '/admin/receitas'
      path: '/receitas'
      fullPath: '/admin/receitas'
      preLoaderRoute: typeof AdminReceitasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/producao': {
      id: '/admin/producao'
      path: '/producao'
      fullPath: '/admin/producao'
      preLoaderRoute: typeof AdminProducaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfis': {
      id: '/admin/perfis'
      path: '/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AdminPerfisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movimentacoes': {
      id: '/admin/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/admin/movimentacoes'
      preLoaderRoute: typeof AdminMovimentacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lista-compras': {
      id: '/admin/lista-compras'
      path: '/lista-compras'
      fullPath: '/admin/lista-compras'
      preLoaderRoute: typeof AdminListaComprasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/indicadores': {
      id: '/admin/indicadores'
      path: '/indicadores'
      fullPath: '/admin/indicadores'
      preLoaderRoute: typeof AdminIndicadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importar-estoque': {
      id: '/admin/importar-estoque'
      path: '/importar-estoque'
      fullPath: '/admin/importar-estoque'
      preLoaderRoute: typeof AdminImportarEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fornecedores': {
      id: '/admin/fornecedores'
      path: '/fornecedores'
      fullPath: '/admin/fornecedores'
      preLoaderRoute: typeof AdminFornecedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/editar/$id': {
      id: '/pedido/editar/$id'
      path: '/editar/$id'
      fullPath: '/pedido/editar/$id'
      preLoaderRoute: typeof PedidoEditarIdRouteImport
      parentRoute: typeof PedidoRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminFornecedoresRoute: typeof AdminFornecedoresRoute
  AdminImportarEstoqueRoute: typeof AdminImportarEstoqueRoute
  AdminIndicadoresRoute: typeof AdminIndicadoresRoute
  AdminListaComprasRoute: typeof AdminListaComprasRoute
  AdminMovimentacoesRoute: typeof AdminMovimentacoesRoute
  AdminPerfisRoute: typeof AdminPerfisRoute
  AdminProducaoRoute: typeof AdminProducaoRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminReceitasRoute: typeof AdminReceitasRoute
  AdminRequisicoesRoute: typeof AdminRequisicoesRoute
  AdminRequisicoesInternasRoute: typeof AdminRequisicoesInternasRoute
  AdminSetoresRoute: typeof AdminSetoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminFornecedoresRoute: AdminFornecedoresRoute,
  AdminImportarEstoqueRoute: AdminImportarEstoqueRoute,
  AdminIndicadoresRoute: AdminIndicadoresRoute,
  AdminListaComprasRoute: AdminListaComprasRoute,
  AdminMovimentacoesRoute: AdminMovimentacoesRoute,
  AdminPerfisRoute: AdminPerfisRoute,
  AdminProducaoRoute: AdminProducaoRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminReceitasRoute: AdminReceitasRoute,
  AdminRequisicoesRoute: AdminRequisicoesRoute,
  AdminRequisicoesInternasRoute: AdminRequisicoesInternasRoute,
  AdminSetoresRoute: AdminSetoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PedidoRouteChildren {
  PedidoEditarIdRoute: typeof PedidoEditarIdRoute
}

const PedidoRouteChildren: PedidoRouteChildren = {
  PedidoEditarIdRoute: PedidoEditarIdRoute,
}

const PedidoRouteWithChildren =
  PedidoRoute._addFileChildren(PedidoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExportarRoute: ExportarRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoricoRoute: HistoricoRoute,
  HistoricoInternoRoute: HistoricoInternoRoute,
  LoginRoute: LoginRoute,
  PedidoRoute: PedidoRouteWithChildren,
  RequisicaoInternaRoute: RequisicaoInternaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolicitarReceitaRoute: SolicitarReceitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
